"""Wire protocol for the browser-facing WebSocket market-stream endpoint:
CandleStreamEvent -> browser JSON encoding, the per-connection heartbeat,
and the reconnect/gap-fill resume decision.

See docs/design/modules/realtime-market-data-stream.md sections 5 and 7,
and docs/plans/realtime-market-data-stream.md (work units 5 and 6).
Deliberately independent of FastAPI/WebSocket/DB so it is directly
testable; see app/api/routes/market_stream_ws.py (work unit 5) for how this
plugs into the actual WS endpoint.

Reconnect wire contract (work unit 6):

- Client -> server, as WS query parameters on `/ws/v1/market-stream`
  alongside `ticket`: `resume_last_sequence` (optional int) and
  `resume_feed_started_at` (optional ISO-8601 datetime) -- a reconnecting
  client's last-seen `sequence` and the `feed_started_at` it was told on
  its PREVIOUS connection (see `encode_stream_state` below). Both must be
  present together to attempt a resume; either one alone is treated as a
  fresh connect (RT-01 semantics), since a partial reconnect state cannot
  be safely interpreted.
- Server -> client, as the first message on every successful connect: a
  `stream_state` envelope (`encode_stream_state`), followed immediately by
  zero or more ordinary event messages (`encode_event`) being replayed,
  before live streaming begins. The client must remember the
  `feed_started_at` from this message, together with the max `sequence` it
  sees afterwards, to attempt a resume on its NEXT reconnect.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Literal
from uuid import UUID, uuid4

from app.market_data.infrastructure.candle_stream import OHLCV, CandleStreamEvent, StreamFeedKey

ResumeMode = Literal["fresh", "replayed", "gap_fill_required"]


def encode_event(event: CandleStreamEvent, workspace_id: UUID) -> dict[str, object]:
    """The browser-facing event JSON (design doc section 5). `workspace_id`
    is stamped here -- the internal CandleStreamEvent/FeedHub
    representation deliberately excludes it (see candle_stream.py module
    docstring): a single feed is shared across every Workspace watching
    it, and only the WS termination layer knows which Workspace a given
    connection belongs to (from its stream ticket)."""
    return {
        "event_id": event.event_id,
        "workspace_id": str(workspace_id),
        "exchange": event.exchange,
        "symbol": event.symbol,
        "timeframe": event.timeframe,
        "sequence": event.sequence,
        "event_type": event.event_type,
        "open_time": event.open_time.isoformat() if event.open_time is not None else None,
        "ohlcv": _encode_ohlcv(event.ohlcv) if event.ohlcv is not None else None,
        "source": event.source,
        "quality": event.quality,
        "reason_code": event.reason_code,
    }


def _encode_ohlcv(ohlcv: OHLCV) -> dict[str, str]:
    return {
        "open": str(ohlcv.open),
        "high": str(ohlcv.high),
        "low": str(ohlcv.low),
        "close": str(ohlcv.close),
        "volume": str(ohlcv.volume),
    }


def encode_heartbeat(
    key: StreamFeedKey, workspace_id: UUID, last_sequence: int, source: str
) -> dict[str, object]:
    """A per-connection liveness ping (design doc section 5: "接続生存確認
    ・遅延計測用"), generated by the WS termination layer itself whenever no
    feed event has arrived for one heartbeat interval -- NOT part of
    FeedHub's own per-feed `sequence` (see candle_stream.py: FeedHub never
    emits an event_type="heartbeat" event itself). Repeats `last_sequence`
    unchanged rather than minting a new one, so a heartbeat never perturbs
    a client's gap-detection bookkeeping (which tracks the max `sequence`
    it has seen)."""
    return {
        "event_id": uuid4().hex,
        "workspace_id": str(workspace_id),
        "exchange": key.exchange,
        "symbol": key.symbol,
        "timeframe": key.timeframe,
        "sequence": last_sequence,
        "event_type": "heartbeat",
        "open_time": None,
        "ohlcv": None,
        "source": source,
        "quality": None,
        "reason_code": None,
    }


def encode_stream_state(feed_started_at: datetime, mode: ResumeMode) -> dict[str, object]:
    """The envelope sent as the very first message on every successful
    connect, before any replayed or live event. Not itself a
    CandleStreamEvent -- distinguished by `"type": "stream_state"` (event
    messages never carry a `type` key)."""
    return {
        "type": "stream_state",
        "feed_started_at": feed_started_at.isoformat(),
        "resume": mode,
    }


@dataclass(frozen=True)
class ResumeRequest:
    """A reconnecting client's remembered state from its previous
    connection. Either field being None means "no previous state" (treated
    as a fresh connect) -- see `is_present`."""

    last_sequence: int | None
    feed_started_at: datetime | None

    @property
    def is_present(self) -> bool:
        return self.last_sequence is not None and self.feed_started_at is not None


@dataclass(frozen=True)
class ResumeDecision:
    mode: ResumeMode
    events_to_replay: list[CandleStreamEvent]


def decide_resume(
    request: ResumeRequest,
    *,
    feed_started_at: datetime,
    buffered_events: list[CandleStreamEvent],
) -> ResumeDecision:
    """See module docstring and design doc section 7 for the protocol this
    implements (RT-07/RT-08)."""
    if not request.is_present:
        # RT-01: first-ever connect for this client, or it chose not to
        # resume. `buffered_events` is just today's normal initial sync
        # (whatever is already in the feed's ring buffer, e.g. if another
        # subscriber's connection kept the feed alive) -- not a gap-fill.
        return ResumeDecision("fresh", list(buffered_events))
    if feed_started_at > request.feed_started_at:
        # The feed the client remembers is gone; a new one was created
        # since (RT-08 -- grace period elapsed and fully tore down, or the
        # API process restarted). The new feed's ring buffer has no
        # continuity with what the client already saw, so nothing here can
        # safely be replayed.
        return ResumeDecision("gap_fill_required", [])
    if buffered_events and buffered_events[0].sequence > request.last_sequence + 1:
        # The same feed survived, but its ring buffer's oldest entry
        # already comes after the client's last-seen sequence + 1 --
        # something in between was evicted (the buffer has a fixed
        # maxlen). Replaying only what remains would leave a silent gap,
        # so fall back to REST gap-fill instead (RT-08).
        return ResumeDecision("gap_fill_required", [])
    # RT-07: the same feed survived and the ring buffer covers the gap in
    # full -- replay exactly what the client missed, nothing more.
    missed = [event for event in buffered_events if event.sequence > request.last_sequence]
    return ResumeDecision("replayed", missed)
